export const usersTemp = [
  {
    id: 0,
    name: "Patryk",
    surname: "Grochowski",
    login: "patryk1234",
    password: 1234,
    role: "user",
    picture: "aaa",
    tasks: [
      {
        usersIDs: [1, 2, 3],
        taskID: 0,
        taskName: "school",
        ToDo: ["zaa a aaaaaaa", "bbb"],
        InProgress: ["ccc", "ddd"],
        Done: ["eee", "fff", "ddd"],
      },
      {
        usersIDs: [1],
        taskID: 1,
        taskName: "work",
        ToDo: ["kill yourself", "bbb"],
        InProgress: ["masturbate", "ddd"],
        Done: ["precum", "fff"],
      },
      {
        usersIDs: [1],
        taskID: 1,
        taskName: "work",
        ToDo: ["kill yourself", "bbb"],
        InProgress: ["masturbate", "ddd"],
        Done: ["precum", "fff"],
      },
      {
        usersIDs: [1],
        taskID: 1,
        taskName: "work",
        ToDo: ["kill yourself", "bbb"],
        InProgress: ["masturbate", "ddd"],
        Done: ["precum", "fff"],
      },
      {
        usersIDs: [1],
        taskID: 1,
        taskName: "work",
        ToDo: ["kill yourself", "bbb"],
        InProgress: ["masturbate", "ddd"],
        Done: ["precum", "fff"],
      },
      {
        usersIDs: [1],
        taskID: 1,
        taskName: "work",
        ToDo: ["kill yourself", "bbb"],
        InProgress: ["masturbate", "ddd"],
        Done: ["precum", "fff"],
      },
      {
        usersIDs: [1, 2, 3, 2],
        taskID: 2,
        taskName: "penice",
        ToDo: ["dsfds", "bbb"],
        InProgress: ["fdsvcxcx", "fcxbxc"],
        Done: ["vcxvcxv", "sadasdasd"],
      },
      {
        usersIDs: [1, 2, 3, 7, 5],
        taskID: 3,
        taskName: "ay lmao",
        ToDo: ["dsad", "vcxvxv"],
        InProgress: ["vcxvcxvcvxc", "ddd"],
        Done: ["vcxvxc", "fff"],
      },
    ],
  },
  {
    id: 1,
    name: "Rafal",
    surname: "Gulewski",
    login: "rafal321",
    password: 4321,
    role: "user",
    picture: "bbb",
    tasks: [
      {
        taskID: 0,
        task: "",
        ToDo: [],
        InProgress: [],
        Done: [],
      },
    ],
  },
];
